server:
  port: 7777


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-not-delete-value: 0
      logic-delete-value: 1
      id-type: auto

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: dengwei

oss:
  accessKey: kF0_oYg1MrGDnDdmrTDzpOcDueS9pdOnATw1BfeE
  secretKey: fGRdkG4NRC10imLFIcNcxnLKemqVqtv-IjdZnkqO
  bucket: dwblog-v1

